Updates to packaging and bootstrap scripts to be consistant and more robust on all unix platforms
git-svn-id: svn+ssh://repo.cacti.net/var/data/svnroot/cacti/spine/branches/0.8.7@5137 860744bd-22fc-0310-8c96-e9fe5004b5ca

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,4 +1,4 @@
-#!/bin/ksh
+#!/bin/sh
 #
 # ----------------------------------------------------------
 # Name: bootstrap
@@ -15,107 +15,75 @@
 #              but simply a supplement.
 #
 # ----------------------------------------------------------
-# Set debugging
-# ----------------------------------------------------------
-#set -x
 
-# ----------------------------------------------------------
 # Help function
-# ----------------------------------------------------------
 display_help () {
-  echo "Spine bootstrap build function"
-  echo "Attempts to build spine based on 'normal' system"
-  echo "If you install things in non-common locations"
-  echo "you may have to use the install instructions to"
-  echo "build."
+  echo "--------------------------------------------------------------"
+  echo "Spine bootstrap & build script"
+  echo "  Attempts to build spine based on a 'normal' system. If you"
+  echo "  install things in non-common locations you may have to use"
+  echo "  the install instructions to build."
+  echo "--------------------------------------------------------------"
+  echo 
 }
 
-# ----------------------------------------------------------
 # Check for parameters
-# ----------------------------------------------------------
-if [ "${1}x" == "--helpx" ]; then
+if [ "${1}x" == "--helpx" -o "${1}x" == "-hx" ]; then
   display_help
   exit 0
 fi
 
-# ----------------------------------------------------------
+# Check for dos2unix
+which dos2unix > /dev/null 2>&1
+[ $? -gt 0 ] && echo "FATAL: Unable to locate dos2unix utility" && exit -1
+
+echo "INFO: Starting Spine build process"
+
 # Remove software build specific directories
-# ----------------------------------------------------------
-echo "--------------------------------------------------------------"
-echo "Spine build process is beginnning"
-echo "--------------------------------------------------------------"
-echo "NOTE: Removing hardware specific directories"
+echo "INFO: Removing cache directories"
 rm -rf autom4te.cache .deps
 
-# ----------------------------------------------------------
-# Get rid of nasty Microsoftisms
-# ----------------------------------------------------------
-if [ `which dos2unix` != "" ]; then
-  echo "--------------------------------------------------------------"
-  echo "NOTE: Performing a dos2unix conversion of all files"
-  for FILE in `ls`; do
-    if [ ! -d $FILE ]; then
-      dos2unix $FILE > /dev/null 2>&1
-    fi
-  done
+# Make sure all files are unix formatted files 
+find . -type f -exec dos2unix \{\} \; > /dev/null 2>&1
 
-  for FILE in `ls config`; do
-    if [ -d $FILE ]; then
-      dos2unix $FILE > /dev/null 2>&1
-    fi
-  done
-else
-  echo "--------------------------------------------------------------"
-  echo "NOTE: dos2unix not found, not double checking file formats"
-fi
-
-# ----------------------------------------------------------
 # Make sure things are executable if they exist
-# ----------------------------------------------------------
-echo "--------------------------------------------------------------"
-echo "NOTE: Setting some permissions"
-[ -f ./configure ] && chmod +x configure
+echo "INFO: Setting permissions"
+[ -f ./configure ] && chmod +x configure > /dev/null 2>&1
 
-# ----------------------------------------------------------
 # Prepare a build state
-# ----------------------------------------------------------
-echo "--------------------------------------------------------------"
-echo "NOTE: Running auto-tools to verify buildability"
+echo "INFO: Running auto-tools to verify buildability"
 aclocal
-[ $? -ne 0 ] && echo "FATAL: aclocal has errors" && exit -1
+[ $? -ne 0 ] && echo "ERROR: 'aclocal' exited with errors" && exit -1
 
 libtoolize --force
-[ $? -ne 0 ] && echo "FATAL: libtool has errors" && exit -1
+[ $? -ne 0 ] && echo "ERROR: 'libtool' exited with errors" && exit -1
 
 autoheader
-[ $? -ne 0 ] && echo "FATAL: autoheader has errors" && exit -1
+[ $? -ne 0 ] && echo "ERROR: 'autoheader' exited with errors" && exit -1
 
 automake --foreign --add-missing --copy
-[ $? -ne 0 ] && echo "FATAL: automake has errors" && exit -1
+[ $? -ne 0 ] && echo "ERROR: 'automake' exited with errors" && exit -1
 
 autoconf
-[ $? -ne 0 ] && echo "FATAL: autoconf has errors" && exit -1
+[ $? -ne 0 ] && echo "ERROR: 'autoconf' exited with errors" && exit -1
 
-# ----------------------------------------------------------
-# perform the build
-# ----------------------------------------------------------
-echo "--------------------------------------------------------------"
-echo "NOTE: Performing build of spine"
-echo "--------------------------------------------------------------"
-./configure --sysconfdir=/etc/cacti --bindir=/usr/sbin
+# Perform the build
+echo "INFO: Performing build of spine"
 make clean
+./configure 
+[ $? -ne 0 ] && echo "ERROR: './configure' exited with errors" && exit -1
+make 
+[ $? -ne 0 ] && echo "ERROR: 'make' exited with errors" && exit -1
 make install
-sleep 3
-clear
+[ $? -ne 0 ] && echo "ERROR: 'make install' exited with errors" && exit -1
 
-# ----------------------------------------------------------
 # Provide some meaningful notes
-# ----------------------------------------------------------
-echo "--------------------------------------------------------------"
-echo "Spine build process complete!!!"
-echo "--------------------------------------------------------------"
-echo "NOTE: Spine has been installed in /usr/bin"
-echo "NOTE: A spine config file has been located in /etc"
-echo "NOTE: This file must be renamed from spine.conf.dist to"
-echo "NOTE: spine.conf and then updated to include the correct"
-echo "NOTE: settings for you cacti install."
+echo "INFO: Spine build process complete"
+echo ""
+echo "INFO: Spine has been installed in /usr/local/spine/bin/"
+echo "INFO: A spine config file has been placed in /usr/local/spine/etc/"
+echo "INFO: This file must be renamed from spine.conf.dist to"
+echo "INFO: spine.conf and then updated to include the correct"
+echo "INFO: settings for you cacti install."
+
+exit 0
diff --git a/package b/package
--- a/package
+++ b/package
@@ -1,63 +1,135 @@
-#!/bin/ksh
+#!/bin/sh
 
-VERSION=`cat configure.ac | grep AM_INIT_AUTOMAKE | awk -F, '{print $2}' | tr -d ')' | tr -d ' '` 
-clear
-# ----------------------------------------------------------
-# Perform packaging
-# ----------------------------------------------------------
-/bin/rm -rf /tmp/cacti-spine-$VERSION /tmp/cacti-spine-$VERSION.*
-svn export . /tmp/cacti-spine-$VERSION
-cd /tmp/cacti-spine-$VERSION
+# Variable Declaration
+TMP_DIR="/tmp"
 
-echo "-----------------------------------------------------------"
-echo "Spine packager for spine version $VERION"
-echo "spine-$VERSION.tar.gz will be placed in /tmp"
-echo "--------------------------------------------------------------"
-echo "Spine package process is beginnning"
-echo "--------------------------------------------------------------"
-echo "NOTE: Removing hardware specific directories"
-/bin/rm -rf autom4te.cache .deps
+# Help Display function
+display_help () {
+  echo "----------------------------------------------------------------------------"
+  echo " Spine Package Script"
+  echo "   Attempts to package spine from a SVN checkout directory of"
+  echo "   spine. If all goes well a tar.gz file will be created."
+  echo "----------------------------------------------------------------------------"
+  echo " Syntax:"
+  echo "  ./`basename $0` <Version> <SVN Revision>"
+  echo ""
+  echo "    <Version> - Designated version for build (required)"
+  echo "    <SVN Revision> - SVN revision number to create build from (optional)"
+  echo ""
+}
 
-# ----------------------------------------------------------
-# Get rid of nasty Microsoftisms
-# ----------------------------------------------------------
-if [ `which dos2unix` != "" ]; then
-  echo "--------------------------------------------------------------"
-  echo "NOTE: Performing a dos2unix conversion of all files"
-  for FILE in `ls`; do 
-    if [ ! -d $FILE ]; then
-      dos2unix $FILE > /dev/null 2>&1
-    fi
-  done
-  
-  for FILE in `ls config`; do
-    if [ -d $FILE ]; then
-      dos2unix $FILE > /dev/null 2>&1
-    fi
-  done
-else
-  echo "--------------------------------------------------------------"
-  echo "NOTE: dos2unix not found, not double checking file formats"
+# Sanity checks
+[ ! -e configure.ac ] && echo "ERROR: Your current working directory must be the SVN check out of Spine" && exit -1
+
+which unix2dos > /dev/null 2>&1;
+[ $? -gt 1 ] && echo "ERROR: Can not locate utility unix2dos" && exit -1
+
+if [ "${1}x" = "--helpx" -o "${1}x" = "-hx" ]; then
+  display_help
+  exit 0
 fi
 
-# ----------------------------------------------------------
-# Make sure things are executable if they exist
-# ----------------------------------------------------------
-echo "--------------------------------------------------------------"
-echo "NOTE: Setting some permissions"
-/bin/rm -f configure
+if [ -z "${1}" ]; then
+  echo ""
+  echo "ERROR: Invalid syntax, missing required argument"
+  echo ""
+  display_help
+  exit -1
+fi
+VERSION=${1}
+
+SVN_REV=""
+[ -n "${2}" ] && SVN_REV="-r ${2}"
+
+# Perform packaging
+echo ""
+echo "----------------------------------------------------------------------------"
+echo "Spine package builder"
+echo "  Version: ${VERSION}"
+echo "----------------------------------------------------------------------------"
+
+# Clean up previous builds
+if [ -e ${TMP_DIR}/cacti-spine-${VERSION} ]; then
+  echo "INFO: Removing previous build ${TMP_DIR}/cacti-spine-${VERSION}..."
+  rm -Rf ${TMP_DIR}/cacti-spine-${VERSION} > /dev/null 2>&1
+  [ $? -gt 1 ] && echo "ERROR: Unable to remove directory: ${TMP_DIR}/cacti-spine-${VERSION}" && exit -1
+fi
+if [ -e ${TMP_DIR}/cacti-spine-${VERSION}.tar.gz ]; then
+  rm -Rf ${TMP_DIR}/cacti-spine-${VERSION}.tar.gz > /dev/null 2>&1
+  [ $? -gt 1 ] && echo "ERROR: Unable to remove file: ${TMP_DIR}/cacti-spine-${VERSION}.tar.gz" && exit -1
+fi
+
+# Copy svn 
+svn export ${SVN_REV} . ${TMP_DIR}/cacti-spine-${VERSION} > /dev/null 2>&1
+[ $? -gt 0 ] && echo "ERROR: Unable to export SVN to ${TMP_DIR}/cacti-spine-${VERSION}" && exit -1
+
+# Change working directory 
+pushd ${TMP_DIR}/cacti-spine-${VERSION} > /dev/null 2>&1
+
+# Build cleanup
+echo "INFO: Removing hardware specific directories..."
+rm -rf autom4te.cache .deps > /dev/null 2>&1
+
+# Get version from source files, warn if different than defined for build
+SRC_VERSION=`cat configure.ac | grep AM_INIT_AUTOMAKE | awk -F, '{print $2}' | tr -d ')' | tr -d ' '` 
+if [ "${SRC_VERSION}" != "${VERSION}" ]; then
+  echo "WARNING: Build version and source version are not the same";
+  echo "WARNING:    Build Version: ${VERSION}"
+  echo "WARNING:   Source Version: ${SRC_VERSION}"
+fi
+
+# Update config file location
+perl -pi -e 's/spine.conf.dist/spine.conf/' Makefile.am > /dev/null 2>&1
+mv spine.conf.dist spine.conf > /dev/null 2>&1
+
+# Convert files to unix format 
+echo "INFO: Converting files to unix format..."
+find . -type f -exec dos2unix \{\} \; > /dev/null 2>&1
+
+# Build it
+echo "INFO: Building..."
+/bin/rm -f configure > /dev/null 2>&1
+
 aclocal
+[ $? -gt 0 ] && echo "FATAL: aclocal has errors" && exit -1
+
 autoheader
+[ $? -gt 0 ] && echo "FATAL: autoheader has errors" && exit -1
+
 automake --add-missing
+[ $? -gt 0 ] && echo "FATAL: automake has errors" && exit -1
+
 libtoolize --force
+[ $? -gt 0 ] && echo "FATAL: libtoolize has errors" && exit -1
+
 autoconf
+[ $? -gt 0 ] && echo "FATAL: autoconf has errors" && exit -1
+
+# Fix permission
+echo "INFO: Fixing permissions..."
+chmod +x configure > /dev/null 2>&1
+find . -name "*.c" -exec chmod 644 \{\} \; > /dev/null 2>&1
+
+# Check working directory
 cd ..
 
-tar -zcf  cacti-spine-$VERSION.tar.gz cacti-spine-$VERSION
-zip -lrq cacti-spine-$VERSION.zip cacti-spine-$VERSION/*
-/bin/rm -rf /tmp/cacti-spine-$VERSION
-cd -
-echo "--------------------------------------------------------------"
-echo "NOTE: Done!!!"
-echo "--------------------------------------------------------------"
+# Package it
+echo "INFO: Packaging..."
+tar -zcf cacti-spine-${VERSION}.tar.gz cacti-spine-${VERSION} 
+[ $? -gt 1 ] && echo "ERROR: Unable to package" && exit -1
+
+# Change working directory
+popd > /dev/null 2>&1
+
+# Clean up
+echo "INFO: Cleaning up build directory..."
+#rm -rf ${TMP_DIR}/cacti-spine-${VERSION} > /dev/null 2>&1
+
+# Display file locations
+echo "INFO: Completed..."
+echo ""
+echo "Package file: ${TMP_DIR}/cacti-spine-${VERSION}.tar.gz"
+echo ""
+
+exit 0
 
