-bug: Net-snmp versioning breaks snmpV3 -feature: Add more config directories for packagers -feature: Install spine in /usr/sbin as this should not be run by users
git-svn-id: svn+ssh://repo.cacti.net/var/data/svnroot/cacti/spine/branches/0.8.7@4990 860744bd-22fc-0310-8c96-e9fe5004b5ca

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -84,6 +84,9 @@ echo "NOTE: Running auto-tools to verify buildability"
 aclocal
 [ $? -ne 0 ] && echo "FATAL: aclocal has errors" && exit -1
 
+libtoolize --force
+[ $? -ne 0 ] && echo "FATAL: libtool has errors" && exit -1
+
 autoheader
 [ $? -ne 0 ] && echo "FATAL: autoheader has errors" && exit -1
 
@@ -93,16 +96,13 @@ automake --foreign --add-missing --copy
 autoconf
 [ $? -ne 0 ] && echo "FATAL: autoconf has errors" && exit -1
 
-libtoolize --force
-[ $? -ne 0 ] && echo "FATAL: libtool has errors" && exit -1
-
 # ----------------------------------------------------------
 # perform the build
 # ----------------------------------------------------------
 echo "--------------------------------------------------------------"
 echo "NOTE: Performing build of spine"
 echo "--------------------------------------------------------------"
-./configure --sysconfdir=/etc --bindir=/usr/bin
+./configure --sysconfdir=/etc/cacti --bindir=/usr/sbin
 make clean
 make install
 sleep 3
